# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3e64b31eae03cfa7e5bb1a5f725592e27ea7d013e16d21a8a4e8ced75d4fb18af754a9f10f4906cc47c0377aa8ecf4eef2e68004be00ee287194acf24cf867c

test:
  secret_key_base: 8a546cc579b497297854612351267c005e996478a8bee5406e8f6c9ae697dafd45063cd6570de87e25b6ed1868fcbecbb4cfe07e851b1f19fc81b24368a0ba49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
